name: 'Run Many'
description: 'Runs the correct NX projects'
author: 'Tycho Bokdam'
runs:
  using: 'node20'
  main: './dist/index.js'

inputs:
  tag:
    description: 'tag'
    required: false

  target:
    description: 'target'
    required: true

  index:
    description: 'index'
    required: false

  count:
    description: 'count'
    required: false

  parallel:
    description: 'parallel'
    required: false

  preTargets:
    description: 'Targets to run before'
    required: false

  postTargets:
    description: 'Targets to run after'
    required: false

  includeLibs:
    description: 'Also include affected libs'
    required: false

  config:
    description: 'With what config to run'
    required: false

  workingDirectory:
    description: 'Optionally define sub directory'
    required: false

  affectedOnly:
    description: 'Only run for affected projects'
    required: true
    default: 'true'
