name: Release

on:
  push:
    branches:
      - master

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:

  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

  release:
    needs: [ prepare-env ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: GIT/NPM config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: ./actions/set-shas
        with:
          main-branch-name: master

      - name: nx affected:version
        uses: ./actions/run-many
        with:
          target: version

      - name: nx affected:build
        uses: ./actions/run-many
        with:
          target: build

      - name: nx affected:publish
        uses: ./actions/run-many
        with:
          target: publish

      - name: Push GIT
        if: always()
        run: git push --follow-tags
